#
# This cloudbuild config runs whenever we push code to master or release
# and updates the target cluster (specified via the $_CLUSTER envrionment
# variable).
#
steps:
# Pull the current latest image, so we can use its cached layers.
- id: 'pull'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args: [
    '-c',
    'docker pull gcr.io/$PROJECT_ID/$REPO_NAME:latest || exit 0'
  ]
# Build the Docker image and tag with the current SHA and latest.
- id: 'build'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
    '.'
  ]
# Push the image tagged by the SHA
- id: 'push'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
  ]
# Generate our Kubernetes configuration
- id: 'config'
  name: 'gcr.io/ai2-reviz/jsonnet'
  args: [
    'eval',
    '-y',
    '--output-file', './webapp.json',
    '--ext-str', 'env=$_ENV',
    '--ext-str', 'image=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
    '--ext-str', 'sha=$COMMIT_SHA',
    '--ext-str', 'buildId=$BUILD_ID',
    '--ext-str', 'repo=$REPO_NAME',
    './webapp.jsonnet'
  ]
  dir: '.skiff'
# Deploy the image to Kubernetes
- id: 'deploy'
  name: 'gcr.io/ai2-reviz/rudder'
  args: [
    'deploy',
    '-f',
    'webapp.json'
  ]
  dir: '.skiff'
substitutions:
  _ENV: staging
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
]
artifacts:
  objects:
    location: 'gs://skiff-archive/$REPO_NAME/$_ENV/$COMMIT_SHA/$BUILD_ID'
    paths: ['.skiff/webapp.json']
timeout: 1800s
