version: 2
updates:
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
