version: 2
updates:
- package-ecosystem: npm
  directory: "/demo"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
