version: '3'
services:
    # These two services return information the front-end needs, and are more likely to be
    # something that we change while working on the UI, so we include them here too.
    model_cards:
        build:
            context: api
            args:
                MODULE: model_cards
        environment:
            - FLASK_ENV=development
        volumes:
            - ./api/allennlp_demo/model_cards:/app/allennlp_demo/model_cards
            - ./api/allennlp_demo/common:/app/allennlp_demo/common
        ports:
            - 8002:8000
    tasks:
        build:
            context: api
            args:
                MODULE: tasks 
        environment:
            - FLASK_ENV=development
        volumes:
            - ./api/allennlp_demo/tasks:/app/allennlp_demo/tasks
            - ./api/allennlp_demo/common:/app/allennlp_demo/common
        ports:
            - 8003:8000
    # Local environments run a HTTP server provided with our JavaScript build tools. It handles
    # incremental recompilation. In production the precompiled UI assets are served from disk
    # via NGINX.
    ui:
        build:
            context: ui
            dockerfile: Dockerfile.dev
        environment:
            - NODE_ENV=development
        # We can't mount ./ui into the container in full, as it might include
        # node_modules/ from the host. This causes weird things to happen.
        # Dependency updates will require the image to be rebuilt to be
        # applied.
        volumes:
            - ./ui/public:/ui/public
            - ./ui/src:/ui/src
        # This is required to keep the UI development server running. We can remove this
        # once port to our newer UI build toolkit.
        tty: true
    # We use a reverse proxy that sends API requests to production, and requests related
    # to the UI to our local instance.
    nginx:
        image: nginx:1.17.10-alpine
        volumes:
            - ./dev/prod_models.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        depends_on:
            - ui
            - model_cards
            - tasks
