# 
# This compose file runs the Integration Tests defined in `it/`. It's not designed to be
# ran in isolation, instead you'll want to run the service in addition to one of the other
# docker-compose configuration. For instance, to run the tests against a local version
# of the UI, where most requests are proxied to the production site, run:
#
#   docker-compose -f docker-compose.ui-only.yaml -f docker-compose.it.yaml
#   docker-compose -f docker-compose.it.yaml exec it -T yarn test:it
# 
# For more on how the multi-compose file mechanism works, see: 
# https://docs.docker.com/compose/extends/
#
version: '3'
services:
    it: 
        build: it
        # This keeps the container alive, so we don't have to start and stop it everytime we
        # want to run the tests.
        entrypoint: 
            - tail
        command:
            - -f
            - /dev/null
        depends_on:
            - nginx

