import React from 'react';
import { Input } from 'antd';

import { Form, Field, Fields, Output, Result, Submit } from '../tugboat/components';
import { InterpreterId } from '../lib';

interface Props<I, O> {
    input: I;
    interpreter: string;
    children: (interpretation: Result<I, O>) => React.ReactNode | JSX.Element;
}

export const Interpret = <I extends { [k: string]: any }, O>({
    interpreter,
    input,
    children,
}: Props<I, O>) => (
    <>
        {getDescription(interpreter)}
        <Form<I, O> action={(modelId) => `/api/${modelId}/interpret/${interpreter}`}>
            <Fields>
                {Object.keys(input).map((fieldName) => (
                    <Field key={fieldName} name={fieldName} hidden>
                        <Input value={input[fieldName]} />
                    </Field>
                ))}
                <Submit>Interpret Prediction</Submit>
            </Fields>
            <Output>{children}</Output>
        </Form>
    </>
);

export const getDescription = (interpreter: string) => {
    switch (interpreter) {
        case InterpreterId.SimpleGradient:
            return (
                <p>
                    See saliency map interpretations generated by{' '}
                    <a
                        href="https://arxiv.org/abs/1312.6034"
                        target="_blank"
                        rel="noopener noreferrer">
                        visualizing the gradient
                    </a>
                    .{' '}
                </p>
            );
        case InterpreterId.IntegratedGradient:
            return (
                <p>
                    See saliency map interpretations generated using{' '}
                    <a
                        href="https://arxiv.org/abs/1703.01365"
                        target="_blank"
                        rel="noopener noreferrer">
                        Integrated Gradients
                    </a>
                    .
                </p>
            );
        case InterpreterId.SmoothGradient:
            return (
                <p>
                    See saliency map interpretations generated using{' '}
                    <a
                        href="https://arxiv.org/abs/1706.03825"
                        target="_blank"
                        rel="noopener noreferrer">
                        SmoothGrad
                    </a>
                    .
                </p>
            );
        default:
            return null;
    }
};
