name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  api_checks:
    name: API Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('api/requirements.txt') }}-${{ hashFiles('api/dev-requirements.txt') }}

    - name: Install requirements
      working-directory: api
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt -r dev-requirements.txt

    - name: Debug info
      run: |
        pip freeze

    - name: Format
      working-directory: api
      if: always()
      run: |
        make format

    - name: Lint
      working-directory: api
      if: always()
      run: |
        make lint

    - name: Type check
      working-directory: api
      if: always()
      run: |
        make typecheck

  endpoint_test:
    name: Endpoint Test
    runs-on: [self-hosted]
    strategy:
      matrix:
        model: [
          "atis_parser",
          "bidaf",
          "bidaf_elmo",
          "constituency_parser",
          "coref",
          "dependency_parser",
          "elmo_snli",
          "fine_grained_ner",
          "glove_sentiment_analysis",
          "masked_lm",
          "named_entity_recognition",
          "naqanet",
          "next_token_lm",
          "nlvr_parser",
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Build and test endpoint
      working-directory: api
      run: |
        make ${{ matrix.model }}-test DOCKER_TAG=$GITHUB_SHA
