name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  api_checks:
    name: API Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('api/requirements.txt') }}-${{ hashFiles('api/dev-requirements.txt') }}

    - name: Install requirements
      working-directory: api
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt -r dev-requirements.txt

    - name: Debug info
      run: |
        pip freeze

    - name: Format
      working-directory: api
      if: always()
      run: |
        make format

    - name: Lint
      working-directory: api
      if: always()
      run: |
        make lint

    - name: Type check
      working-directory: api
      if: always()
      run: |
        make typecheck

  endpoint_test:
    name: Endpoint Test
    runs-on: [self-hosted]
    strategy:
      matrix:
        model: [
          "atis_parser",
          "bidaf",
          "bidaf_elmo",
          "constituency_parser",
          "coref",
          "dependency_parser",
          "elmo_snli",
          "fine_grained_ner",
          "glove_sentiment_analysis",
          "masked_lm",
          "named_entity_recognition",
          "naqanet",
          "next_token_lm",
          "nlvr_parser",
          "nmn_drop",
          "open_information_extraction",
          "roberta_mnli",
          "roberta_sentiment_analysis",
          "roberta_snli",
          "semantic_role_labeling",
          "transformer_qa",
          "vilbert_vqa",
          "wikitables_parser",
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Build and test endpoint
      working-directory: api
      run: |
        make ${{ matrix.model }}-test DOCKER_TAG=$GITHUB_SHA

  validate_ci:
    name: Validate CI Config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip install PyYAML

    - name: Validate GitHub Actions config
      run: |
        # If this step fails, this means the model matrix in the 'endpoint_test' GitHub Actions
        # job needs to be updated.
        python dev/check_models_ci.py
