name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  api_checks:
    name: API Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('api/requirements.txt') }}-${{ hashFiles('api/dev-requirements.txt') }}

    - name: Install requirements
      working-directory: api
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt -r dev-requirements.txt

    - name: Debug info
      run: |
        pip freeze

    - name: Format
      working-directory: api
      if: always()
      run: |
        make format

    - name: Lint
      working-directory: api
      if: always()
      run: |
        make lint

    - name: Type check
      working-directory: api
      if: always()
      run: |
        make typecheck

  atis_parser:
    name: Endpoint Test (${{ github.job }})
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Build and test endpoint
      working-directory: api
      run: |
        make ${{ github.job }}-test DOCKER_TAG=$GITHUB_SHA

  bidaf:
    name: Endpoint Test (${{ github.job }})
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: Build and test endpoint
      working-directory: api
      run: |
        make ${{ github.job }}-test DOCKER_TAG=$GITHUB_SHA
