name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  # Runs common light-weight checks like linting and type checking.
  api_checks:
    name: API Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/cache@v1
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('api/requirements.txt') }}-${{ hashFiles('api/dev-requirements.txt') }}

    - name: Install requirements
      run: |
        cd api
        pip install --upgrade --upgrade-strategy eager -r requirements.txt -r dev-requirements.txt

    - name: Format
      if: always()
      run: |
        cd api && make format

    - name: Lint
      if: always()
      run: |
        cd api && make lint

    - name: Type check
      if: always()
      run: |
        cd api && make typecheck

  # This is an example of how we could run individual model tests on GitHub Actions.
  # Currently we're doing this as part of the Google Cloud Build since that allows us to
  # filter which models to build based on which files have changed.
  # bidaf:
  #   name: Model (bidaf)
  #   # We run these tests on self-hosted runners because they require huge model
  #   # files. We wouldn't be able to cache all of these using the cache available to GitHub-hosted
  #   # runners, and downloading them from source each time would be become very expensive for us.
  #   runs-on: [self-hosted]
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build and test image
  #     run: |
  #       cd api && make bidaf-test DOCKER_TAG=$GITHUB_SHA
