name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      uses: whoan/docker-build-with-cache-action@v5.0.1
      with:
        image_name: allennlp/demo
        image_tag: latest,${{ github.sha }}
        push_image_and_stages: false

    - name: Run tests
      run: docker run --entrypoint= allennlp/demo pytest tests/

    - name: Pip freeze
      run: docker run --entrypoint= allennlp/demo pip freeze

    - name: Push image
      if: github.repository == 'allenai/allennlp-demo' && github.event_name == 'push'
      uses: whoan/docker-build-with-cache-action@v5.0.1
      with:
        username: allennlpuser
        password: "${{ secrets.DOCKERHUB_ALLENNLPUSER_PASSWORD }}"
        image_name: allennlp/demo
        image_tag: latest,${{ github.sha }}
