name: PR

on:
  pull_request:
    branches:
    - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image with cache
      uses: whoan/docker-build-with-cache-action@v5.0.1
      with:
          username: allennlpuser
          password: "${{ secrets.DOCKERHUB_ALLENNLPUSER_PASSWORD }}"
          image_name: allennlp/allennlp-demo
          image_tag: latest,${{ github.sha }}

    - name: Run tests
      run: docker run --entrypoint= allennlp-demo pytest tests/

    - name: Pip freeze
      run: docker run --entrypoint= allennlp-demo pip freeze
