name: UI CI
on:
  push:
    branches:
    - master
    paths:
    - 'ui/**'
    - 'it/**'
  pull_request:
    branches:
    - master
    paths:
    - 'ui/**'
    - 'it/**'
jobs:
  ui_checks:
    name: UI Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Start application
      run: ./demo start
    - name: Lint UI
      run: ./demo run ui yarn lint
    - name: Run tests
      run: ./demo it
