name: UI CI
on:
  push:
    branches:
    - master
    paths:
    - 'ui/**'
    - 'it/**'
  pull_request:
    branches:
    - master
    paths:
    - 'ui/**'
    - 'it/**'
jobs:
  ui_checks:
    name: UI Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start application
        run: ./demo start
      - name: Lint UI
        run: ./demo ui yarn lint
      - name: Run tests
        run: ./demo it

